---
# tasks file for linuxdemo
- name: copy the shell file to genrate report on target servers
  ansible.builtin.copy:
    src: report.sh
    dest: /tmp/report.sh
    owner: root
    group: root
    mode: u+rwx,g-rx,o-rx

- name: Execute the Shell script to Genrate report
  shell: "wget https://raw.github.com/tdulcet/Linux-System-Information/master/info.sh -qO - | bash -s >> /tmp/report.txt"


- name: Display /tmp/report.txt contents
  command: cat report.txt chdir=/tmp
  register: command_output

- name: Print to console
  debug:
    msg: "{{command_output.stdout_lines}}"

#- name: Fetch all details in files
#  fetch:
#    src: /tmp/report.txt 
#    dest: files/ 
#    fail_on_missing: True 
#    validate_checksum: True 
#    flat: true 
