---
- name: Debug AAP
  hosts: all
  tasks:
   # - debug:
    #    var: vars
        
    - set_fact:
        job_id: "{{ lookup('env', 'JOB_ID') | int }}"
   
    - set_fact:
        job_api: "{{ lookup('ansible.controller.controller_api', 'jobs/{{ job_id }}', host='aap1.example.com',
                                  username='admin', password='primod123', verify_ssl=False) }}"
                                  
    - name: Running Hostname command to confirm and no funny bussness
      ansible.builtin.shell: hostname
      register: hostname

    - name: Show debug output
      ansible.builtin.debug:
        msg: "{{hostname.stdout}}"

    - name: Running ifconfig command to confirm and no funny bussness
      ansible.builtin.shell: ifconfig
      register: ifg

    - name: Show debug output
      ansible.builtin.debug:
        msg: "{{ifg.stdout}}"
        


#- name: Arcon Ansible Demo setup
#  hosts: localhost
# # ansible_connection: local
#  vars:
#    pwd: "{{ lookup('arconplugin','/runner/inventory/hosts',wantlist=False) }}"
#  tasks:
#    - debug: msg="{{ pwd }}"

