---
- name: Debug AAP
  hosts: all
  tasks:
   # - debug:
    #    var: vars
        
    - set_fact:
        job_id: "{{ lookup('env', 'JOB_ID') | int }}"
   
    #- name: Load the UI settings specifying the connection info
    #  set_fact:
    #    controller_settings: "{{ lookup('awx.awx.controller_api', 'settings/ui', host='192.168.1.9',
    #                              username='admin', password='primod123', verify_ssl=False) }}"

    - set_fact:
        job_api: "{{ lookup('ansible.controller.controller_api', 'jobs/{{ job_id }}', host='192.168.1.9',
                                  username='admin', password='primod123', verify_ssl=False) }}"

    - debug:
        var: job_api
        
---
- hosts: localhost
  become: yes
  gather_facts: no
  connection: local
  tasks:
    - name: disply pass
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/dev:pass token=hvs.PCEHQBAGA1l8C3aX5QNmXt2E url=http://192.168.1.13:8200') }}"
      register: secret_data


    - debug: 
        msg: "{{ secret_data.msg }}"
