---
- name: Debug AAP
  hosts: all
  tasks:                                  
    - name: Running Hostname command to confirm and no funny bussness
      ansible.builtin.shell: hostname
      register: hostname

    - name: Show debug output
      ansible.builtin.debug:
        msg: "{{hostname.stdout}}"

    - name: Running ifconfig command to confirm and no funny bussness
      ansible.builtin.shell: ip addr
      register: ifg

    - name: Show debug output
      ansible.builtin.debug:
        msg: "{{ifg.stdout}}"
        


#- name: Arcon Ansible Demo setup
#  hosts: localhost
# # ansible_connection: local
#  vars:
#    pwd: "{{ lookup('arconplugin','/runner/inventory/hosts',wantlist=False) }}"
#  tasks:
#    - debug: msg="{{ pwd }}"

