---
- name: building solution using jinja2
  hosts: localhost
  tasks:
    - name: Building a jinja Template
      ansible.builtin.template:
        src: inventory.j2
        dest: /runner/inventory/inventory
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        
    - name: display the ini inventory
      shell: "cat /runner/inventory/inventory"
      register: ini_inv

    - name: disply the inventory
      debug:
        msg: "{{ ini_inv }}"
    
- name: Arcon Ansible Demo setup
  hosts: localhost
  vars:
    pwd: "{{ lookup('arconplugin','/runner/inventory/inventory@hosts',wantlist=True) }}"
  tasks:
    - debug: 
        msg: "{{ ansible_password }}"

