---
- name: building solution using jinja2
  hosts: localhost
  tasks:
    - name: Building a jinja Template
      ansible.builtin.template:
        src: inventory.j2
        dest: /runner/inventory/inventory
        owner: root
        group: root
        mode: u=rw,g=r,o=r
              
    - name: will lookup in this to set tha pass in variable   
      debug:
        msg: "{{ pwd }}"
      vars:
        pwd: "{{ lookup('arconplugin','/runner/inventory/inventory@hosts',wantlist=True) }}"
    
    
          
- name: Arcon Ansible Demo setup
  hosts: all
#  vars:
#    pwd: "{{ lookup('arconplugin','/runner/inventory/inventory@hosts',wantlist=True) }}"
  tasks:
    - shell: "cat /etc/redhat-release"
      register: release_out

    - debug:
        msg: "{{ release_out }}"
