---
- hosts: all
  become: yes
  gather_facts: no
  tasks:  
    - name: calling a job name to invoke from system
      shell: wget https://google.com
      register: url_output
    
    - name: print debug output
      debug: 
        msg: "{{ url_output }}"    
      
    - name: print the output of some command
      shell: hostname
      register: output_hostname

    - name: print the debug output
      debug:  
        msg: "{{ output_hostname }}"  
   
    - name: calling url of remote site for testing
      shell: "wget {{ siteurl }}"
      register: url_output
      ignore_errors: true

    - name: print debug output
      debug:
        msg: "{{ url_output }}"


    - name: Wait until the string "approved" is in the file /tmp/job before continuing or 1 min
      wait_for:
        path: /tmp/job
        search_regex: approved
        timeout: 60
        
    - name: Check if job file is present   
      stat:
        path: /tmp/job
      register: register_name

    - name: Print Error at last if approval is not given
      debug:
        msg: "{{ url_output }}"
      when: not register_name.stat.exists 

#    - name: mark job success when mark ok workflow is ran 
#      shell: "exit 0"
#      when: "{{ url_output.rc }} != 0"
      
