---
- hosts: all
  become: yes
  gather_facts: no
  tasks:  
    - name: calling a job name to invoke from system
      shell: wget https://google.com
      register: url_output
    
    - name: print debug output
      debug: 
        msg: "{{ url_output }}"    
      
    - name: print the output of some command
      shell: hostname
      register: output_hostname

    - name: print the debug output
      debug:  
        msg: "{{ output_hostname }}"  
   
    - name: calling url of remote site for testing
      shell: "wget {{ siteurl }}"
      register: url_output
      ignore_errors: true

    - name: print debug output
      debug:
        msg: "{{ url_output }}"


   - name: Wait until the string "approved" is in the file /tmp/job before continuing
     wait_for:
       path: /tmp/job
       search_regex: approved    

#    - name: Are you want to mark the job success
#      pause:
#        prompt: "Are you sure you want to mark job success? (yes/no)"
#      register: confirm_delete
#      when: "{{ url_output.rc }} != 0" 

    - name: mark job success when mark ok workflow is ran 
      shell: "exit 0"
      when: "{{ url_output.rc }} != 0"
      
