---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    log_path: /opt/bmc/bladelogic/RSCD/Transactions
  tasks:
    - name: Locating all files in files dir
      find:
        path: "{{ log_path }}"
        file_type: any
     #  age: 2d #4w You can choose seconds, minutes, hours, days, or weeks by the first letter of any of those words (e.g., “1w”).  
      register: cleanup
      ignore_errors: true

    - debug:
        msg: "{{ cleanup.files }}"

    - name : Delete all logs from given paths
      file:
        path: "{{ item.path }}"  
        state: absent
      with_items: "{{ cleanup.files }}"
