---
- hosts: all
  become: yes
  gather_facts: no
  tasks:  
    - set_fact:
        log_path: /home/nrathi/sample
        pattern: "*.txt"


    - name: showig current logs files on path
      shell: "la -la /opt/bmc/bladelogic/RSCD/Transactions/analysis_archive/"
      register: logfiles
    
    - debug:
        msg: logfiles.stdout
        
    - name : Delete all logs from given paths
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob: "{{ log_path }}/{{ pattern }}" 

    - name: showig current logs files on path
      shell: "la -la /opt/bmc/bladelogic/RSCD/Transactions/analysis_archive/"
      register: logfiles
    
    - debug:
        msg: logfiles.stdout
