---
- hosts: all
  become: yes
  gather_facts: no
  tasks:  
    - name: put approved in the /tmp/job file to mark job as success 
      shell: "echo approved >> /tmp/job" 
      register: approvedoutput
    
    - name: print debug output
      debug: 
        msg: "{{ approvedoutput }}"    

   - name: Pause for 5 minutes to build app cache
     ansible.builtin.pause:
       minutes: 1

   - name: Remove approval file (delete file) as after wait of 1 min
     ansible.builtin.file:
       path: /etc/job
       state: absent       
