---
- hosts: all
  become: yes
  gather_facts: no
  tasks:  
    - name: put approved in the /tmp/job file to mark job as success 
      shell: "echo approved >> /tmp/job" 
      register: approvedoutput
    
    - name: print debug output
      debug: 
        msg: "{{ approvedoutput }}"    

    - name: Pause for 10 seconds for other job to read the approval
      ansible.builtin.pause:
        seconds: 2

    - name: Remove approval file (delete file) as after wait of 10 seconds
      ansible.builtin.file:
        path: /tmp/job
        state: absent       
