---
- name: Mark job as approved
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Put approved in the /tmp/job file to mark job as success
      ansible.builtin.lineinfile:
        path: /tmp/job
        line: "approved"
        create: true
        insertafter: EOF
      register: approvedoutput

    - name: Print debug output
      ansible.builtin.debug:
        msg: "{{ approvedoutput }}"

    - name: Pause for 10 seconds for other job to read the approval
      ansible.builtin.pause:
        seconds: 2

    - name: Remove approval file (delete file) as after wait of 10 seconds
      ansible.builtin.file:
        path: /tmp/job
        state: absent
