---
- name: Genrate and set random password
  hosts: all
  name: Generate a password with constraints
  gather_facts: no
  tasks:
    - name: Generate password
      set_fact:
        generated_password: "{{ lookup('community.general.random_string', length=12, min_lower=1, min_upper=1, min_numeric=1, min_special=1, override_special='-_=+!#$()[]') }}"

    - name: Verify the generate password
      debug:
        var: generated_password
        
     - name: Setting password for user
       ansible.builtin.user:
         name: "{{ ansible_user | trim }}"
         password: "{{ generated_password | password_hash('sha512', 'mysecretsalt') }}"        

    
    - name: Write password to Vault using key value V2 engine
      delegate_to: 127.0.0.1
      community.hashi_vault.vault_write:
        path: secret/data/dev/{{inventory_hostname}}
        data:
          data:
            password: "{{ generated_password }}"
               
