---
- name: Genrate and set random password
  hosts: localhost
  name: Generate a password with constraints
  gather_facts: no
  tasks:
    - name: Generate password
      set_fact:
        generated_password: "{{ lookup('community.general.random_string', length=12, min_lower=1, min_upper=1, min_numeric=1, min_special=1, override_special='-_=+!#$()[]') }}"

    - name: Verify the generate password
      debug:
        var: generated_password
