---
- name: Create secretid and retrive roleid
  hosts: all
 # connection: local
  tasks:
#    - name: Retrieve an approle role ID from Vault via the remote host
#      community.hashi_vault.vault_read:
#       # url: https://vault:8201
#        path: "auth/approle/role/{{ rolename }}/role-id"
#      register: approle_id

#    - name: Generate a secret-id for the given approle
#      community.hashi_vault.vault_write:
#        #url: https://vault:8201
#        path: "auth/approle/role/{{ rolename }}/secret-id"
#      register: secret_id

#    - name: Display the role ID and secret ID
#      ansible.builtin.debug:
#        msg:
#          - "role-id: {{ approle_id.data.data.role_id }}"
#          - "secret-id: {{ secret_id.data.data.secret_id }}"

    - set_fact:
        job_id: "{{ lookup('env', 'JOB_ID') | int }}"

    - set_fact:
       # host: "{{ lookup('hashi_vault', 'secret=secret/data/dev/ctrl:host') }} | string"
       # user: "{{ lookup('hashi_vault', 'secret=secret/data/dev/ctrl:user') }} | string"
        pass: "{{ lookup('hashi_vault', 'secret=secret/data/dev/ctrl:pass') }} | string"
        job_api: "{{ lookup('ansible.controller.controller_api', 'jobs/{{ job_id }}', host='192.168.1.11', username='admin', password='{{ pass }}',verify_ssl=False) }}"

    - debug:
        var: job_api.summary_fields.inventory.name
