---
- hosts: localhost
  tasks:
    - name: Seal the vault
      hashivault_seal:
      register: 'vault_seal'
      
    - name : check if vault is seal properly  
      debug: 
        msg: "Seal return is {{vault_seal.rc}}"
