---
- name: Create and delete user
  hosts: all
  vars:
    username: navneet
    password: navneet22
    policies: acl_sa_ansible
    action:
  environment:
    VAULT_ADDR: http://192.168.1.11:8200
  tasks:
    - name: Enable Engine userpass hashicorp vault
      shell: vault auth enable userpass
      ignore_errors: true
      
    - name: Create user set pass and attach policy
      shell: vault write auth/userpass/users/"{{ user |default('navneet', true) }}" password="{{ pass|default('navneet22',true) }}" policies="{{ policies|default('acl_sa_ansible',true) }}"
      when: 
        - action == "create"

    - name: delete user from hashicorpvault
      shell: vault delete auth/userpass/users/{{ user }}
      when: 
        - action == "delete"