---
# tasks file for curl

- name : check if curl is present or not
  shell: "rpm -qa |grep curl"
  register: package_data


- debug:
    msg: {{ package_data.std_out }}

 
- name : removing Curl package from system
  shell: "rpm -e --nodeps curl-7.29.0-46.el7.x86_64"
  register : package_data

- debug:
    msg: {{ package_data.std_out }}
    
- name: copy the shell file to genrate report on target servers
  ansible.builtin.copy:
    src: curl-7.29.0-59.el7_9.2.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: u+rwx,g-rx,o-rx

- name: install curl packge
  yum:
    name: /tmp/curl-7.29.0-59.el7_9.2.x86_64.rpm
    state: present

- name : check if curl is present or not
  shell: "rpm -qa |grep curl"
  register: package_data

- debug:
    msg: {{ package_data.std_out }}
